# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodPracUmair1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftHEXColors'
  pod 'SDWebImage/WebP'
  pod 'Alamofire', '~> 4.0'
  pod 'INSPersistentContainer'
  pod 'RMQClient'
  # Pods for PodPracUmair1

end
